#include<stdio.h>

// Desafio Super Trunfo - Países - teste aula guanabara
// Tema 1 - Cadastro das cartas
// Objetivo: No nível novato você deve criar as cartas representando as cidades utilizando scanf para entrada de dados e printf para exibir as informações.

int main() {
  // Área para definição das variáveis para armazenar as propriedades das cidades
    int Populacao, Populacao2;
    char Estado[20], Estado2[20];
    char Codigo[20], Codigo2[20];
    char Cidade[20], Cidade2[20];
    float Area, Area2;
    float PIB, PIB2;
    int PTuristico, PTuristico2;
    float Densidade1 = Populacao / Area;
    float Densidade2 = Populacao2 / Area2;
    float PIBpercapita1 = PIB / Populacao;
    float PIBpercapita2 = PIB / Populacao2;



    printf("+++++++++++++++++++++++++++++++++++++++++++++++++++\n");
    printf("+++++++++++++++++++++++++++++++++++++++++++++++++++\n");
    printf("*****Olá, você está no SUPER TRUNFO - Países!******\n");
    printf("+++++++++++++++++++++++++++++++++++++++++++++++++++\n");
    printf("+++++++++++++++++++++++++++++++++++++++++++++++++++\n");
    printf("!!!!!!!!  ATENÇÃO PARA AS REGRAS DO JOGO   !!!!!!!!\n");
    printf("\n");
    printf("*************** De Olho Nas Regras *****************\n");
    printf("\n");
    printf("Vamos Começar!?!\n");
      printf("Digite um Estado de sua Escolha \n");
      printf("\n");
        printf("  *** Atenção!!*** - Caso utilize um Estado com nome composto não utilizar espaço em branco, separar com hífem(-), ou Underline(_). Ex.: Rio-de-janeiro, Minas_Gerais\n");
            printf("\n");
              scanf("%s", &Estado);
                printf("Estado: %s \n", &Estado );
                  printf("\n");
                    printf("  ** Atenção!!** - Após escolher o Estado, escolha uma lerta entre A e H que será Código da carta que irá representar esse Estado, ex:. Bahia(B)\n");
                      printf("\n");
    printf("Código da Carta \n");
      printf("\n");
      printf("  **ATENÇÃO!!** - O código da carta deve conter a letra que irá representar o Estado seguida de um número, ex. 1: Estado= São Paulo_letra_A_Código: A01; ex. 2: Bahia_letra_B_Código: B1\n");
        printf("\n");
          printf("Digite o Código da carta: ");
            scanf("%s", &Codigo);
              printf("Código: %s \n", &Codigo);
                printf("\n");      
    printf("Cidade \n");
    printf("\n");
        printf("  ** Atenção!!** \n");
          printf("  - Escolha uma cidade pertencente ao Estado que escolheu anteriormente, ex:. Estado Bahia_cidade_Ilhéus; \n");
          printf("  - Caso utilize uma cidade com nome composto não utilizar espaço em branco, separar com hífem(-), ou Underline(_). Ex.: Rio_de_janeiro, Minas_Gerais \n");
          printf("\n");
            printf("Digite a Cidade: ");
              scanf("%s", &Cidade);
                printf("Cidade: %s \n", &Cidade);
                  printf("\n");
    printf("População \n");
    printf("\n");
      printf("  ** Atenção!!** - Insira a Populção aproximada da cidade escolhida anteriormente;\n");
        printf("Digite a População: ");
          scanf("%d", &Populacao);
            printf("Populacao: %d \n", Populacao);
              printf("\n");
    printf("Área \n");
    printf("\n");
      printf("  ** Atenção!!** - Insira um valor aproximado da densidade demgráfica da CIDADE escolhida anteriormente;\n");
        printf("Digite a Área: ");
          scanf("%f" , &Area);
            printf("Área: %f \n", Area);      
              printf("\n");
    printf("PIB \n");
    printf("\n");
      printf("  ** Atenção!!** - Insira um valor aproximado do PIB da CIDADE escolhida anteriormente;\n");
        printf("Digite o PIB: ");
        scanf("%f", &PIB);
          printf("PIB: %f \n", PIB);
            printf("\n");
    printf("Pontos Turísticos \n");
    printf("\n");
      printf("  ** Atenção!!** - Insira um valor aproximado dos pontos turísticos da CIDADE escolhida anteriormente;\n");
        Printf("Digite o Ponto Turístico: ");
          scanf("%d", &PTuristico);
            printf("Pontos Turísticos: %d \n", PTuristico);
              printf("\n");
                printf("\n");
    printf("lendo dados... \n");
      printf("\n");
        printf("carrregando Carta 1... \n");
          printf("...   ...   ...carregando.\n");
            printf("\n");
              printf("*CARTA 1* \n"); 
                printf("Estado: %s \n", Estado);
                  printf("Código: %s \n", Codigo);
                    printf("Cidade: %s \n", Cidade);
                      printf("População: %d \n", Populacao);
                        printf("Área: %f \n", Area);
                          printf("PIB: %f \n", PIB);
                            printf("Pontos Turísticos: %d \n", PTuristico);
                              printf("Densidade Demografica: %f\n", Densidade1);
                                printf("\n");
    printf("Digite os dados da Carta 2 \n");  
      printf("Digite o Estado:\n");
        scanf("%s", &Estado2);
          printf(" Estado: %d\n", Estado2);
            printf("\n");
    printf("Código da Carta: ");
      scanf("%s", &Codigo2);
        printf("Código: %s \n", Codigo2);
          printf("\n");
    printf("Cidade: ");
      scanf("%s", &Cidade2);
        printf("Cidade: %d\n", Cidade2);
          printf("\n");
    printf("População: ");
      scanf("%d", &Populacao2);
        Printf("População: %f\n", Populacao2);
          printf("\n");
    printf("Área: ");
      scanf("%f", &Area2);
        printf("Área: %f\n", Area);
          printf("\n");
    printf("PIB: ");
      scanf("%f", &PIB2);
        printf("PIB: %f\n", PIB2);
          printf("\n");
    printf("Pontos Turísticos: ");
      scanf("%d", &PTuristico2);
        printf("Pontos Turísticos: \n", PTuristico2);
          printf("\n");
    printf("lendo dados... \n");
      printf("\n");
        printf("carrregando Carta 2... \n");
          printf(" ...   ...   ...carregando\n");
            printf("\n");
              printf("*CARTA 2* \n"); 
                printf("Estado: %s \n", Estado2);
                  printf("Código: %s \n", Codigo2);
                    printf("Cidade: %s \n", Cidade2);
                      printf("População: %d \n", Populacao2);
                        printf("Área: %f \n", Area2);
                          printf("PIB: %f \n", PIB2);
                            printf("Pontos Turísticos: %d \n", PTuristico2);
                              Densidade1 = Populacao2 / Area2;
                                printf("Densidade Demografica: %f\n", Densidade2);
                                  printf("\n");
                                  /*
    printf("Gerando Cartas... \n");
      printf("\n");
    printf("*CARTA 1* \n"); 
      printf("Estado: %s \n", Estado);
        printf("Código: %s \n", Código);
          printf("Cidade: %s \n", Cidade);
            printf("População: %d \n", População);
              printf("Área: %f \n", Área);
                printf("PIB: %f \n", PIB);
                  printf("Pontos Turísticos: %d \n", PTurístico);
                    printf("\n");
    printf("*CARTA 2* \n"); 
      printf("Estado: %s \n", Estado2);
        printf("Código: %s \n", Código2);
          printf("Cidade: %s \n", Cidade2);
            printf("População: %d \n", População2);
              printf("Área: %f \n", Área2);
                printf("PIB: %f \n", PIB2);
                  printf("Pontos Turísticos: %d \n", PTurístico2);
                    printf("\n");
    printf("\n");
    */

  return 0;
}
